import { ContractAbi } from './contract_type';

export const BOLERO_NFT_CONTRACT_ABI_V3: ContractAbi = [
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'symbol', type: 'string' },
      { internalType: 'address', name: 'swap', type: 'address' },
      { internalType: 'address', name: 'managerRegistry', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'approved', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'operator', type: 'address' },
      { indexed: false, internalType: 'bool', name: 'approved', type: 'bool' },
    ],
    name: 'ApprovalForAll',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'string', name: '_tokenURI', type: 'string' },
    ],
    name: 'ChangeTokenURI',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'collectionID', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'artist', type: 'address' },
      { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      { indexed: false, internalType: 'uint256', name: 'boleroFeesPrimary', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'boleroFeesSecondary', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'artistRoyalties', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'cap', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'privateSaleThreshold', type: 'uint256' },
      { indexed: false, internalType: 'bool', name: 'isWithPaymentSplitter', type: 'bool' },
    ],
    name: 'NewCollection',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'artistAddress', type: 'address' },
      { indexed: true, internalType: 'address', name: 'privateSaleToken', type: 'address' },
      { indexed: false, internalType: 'string', name: 'collectionName', type: 'string' },
      { indexed: true, internalType: 'address[]', name: 'payees', type: 'address[]' },
      { indexed: false, internalType: 'string[]', name: 'roles', type: 'string[]' },
      { indexed: false, internalType: 'uint256[]', name: 'shares', type: 'uint256[]' },
      { indexed: false, internalType: 'uint256', name: 'boleroFeesPrimary', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'boleroFeesSecondary', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'artistRoyalties', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'cap', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'privateSaleThreshold', type: 'uint256' },
      { indexed: false, internalType: 'bool', name: 'isWithPaymentSplitter', type: 'bool' },
    ],
    name: 'NewCollectionWithPaymentSplitter',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint256', name: 'tokenID', type: 'uint256' }],
    name: 'SetSecondaryMarket',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'collectionID', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'threshold', type: 'uint256' },
    ],
    name: 'ThresholdUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'approvedContract', type: 'address' },
    ],
    name: 'TokenLocked',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'approvedContract', type: 'address' },
    ],
    name: 'TokenUnlocked',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      { indexed: true, internalType: 'address', name: 'to', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'Transfer',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'newBoleroLockRegistryImplementation',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'newBoleroMultisigImplementation',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'newBoleroPaymentSplitterImplementation',
    type: 'event',
  },
  {
    inputs: [],
    name: 'BoleroMultisig',
    outputs: [{ internalType: 'contract IBoleroMultisig', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAXIMUM_PERCENT',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'PaymentSplitter',
    outputs: [{ internalType: 'contract IBoleroPaymentSplitter', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: '_collectionIds',
    outputs: [{ internalType: 'uint256', name: '_value', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: '_tokenIds',
    outputs: [{ internalType: 'uint256', name: '_value', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'approvedContract',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenID', type: 'uint256' }],
    name: 'artistPayment',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
    name: 'autoLockId',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'bolero',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'boleroMultisigImplementation',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'boleroPaymentSplitterImplementation',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'boleroSwap',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'burn',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_userAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenID', type: 'uint256' },
    ],
    name: 'canSwap',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'string', name: '_tokenURI', type: 'string' },
    ],
    name: 'changeTokenURI',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'collectionForTokenID',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_collectionId', type: 'uint256' }],
    name: 'collectionMultisig',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_collectionId', type: 'uint256' }],
    name: 'collectionPayment',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'collection_byArtist',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'collection_tokensIds',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'collections',
    outputs: [
      { internalType: 'address', name: 'artist', type: 'address' },
      { internalType: 'address', name: 'payment', type: 'address' },
      { internalType: 'address', name: 'privateSaleToken', type: 'address' },
      { internalType: 'string', name: 'collectionName', type: 'string' },
      { internalType: 'uint256', name: 'collectionId', type: 'uint256' },
      { internalType: 'uint256', name: 'cap', type: 'uint256' },
      {
        components: [
          { internalType: 'uint256', name: 'boleroFeesPrimary', type: 'uint256' },
          { internalType: 'uint256', name: 'boleroFeesSecondary', type: 'uint256' },
          { internalType: 'uint256', name: 'artistRoyalties', type: 'uint256' },
        ],
        internalType: 'struct BoleroNFT.Royalties',
        name: 'royalties',
        type: 'tuple',
      },
      { internalType: 'uint256', name: 'privateSaleThreshold', type: 'uint256' },
      { internalType: 'bool', name: 'isWithPaymentSplitter', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'getApproved',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getApprovedContracts',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenID', type: 'uint256' }],
    name: 'getCollectionForToken',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'artist', type: 'address' },
          { internalType: 'address', name: 'payment', type: 'address' },
          { internalType: 'address', name: 'privateSaleToken', type: 'address' },
          { internalType: 'string', name: 'collectionName', type: 'string' },
          { internalType: 'uint256', name: 'collectionId', type: 'uint256' },
          { internalType: 'uint256', name: 'cap', type: 'uint256' },
          {
            components: [
              { internalType: 'uint256', name: 'boleroFeesPrimary', type: 'uint256' },
              { internalType: 'uint256', name: 'boleroFeesSecondary', type: 'uint256' },
              { internalType: 'uint256', name: 'artistRoyalties', type: 'uint256' },
            ],
            internalType: 'struct BoleroNFT.Royalties',
            name: 'royalties',
            type: 'tuple',
          },
          { internalType: 'uint256', name: 'privateSaleThreshold', type: 'uint256' },
          { internalType: 'bool', name: 'isWithPaymentSplitter', type: 'bool' },
        ],
        internalType: 'struct BoleroNFT.Collection',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenID', type: 'uint256' }],
    name: 'getCollectionIDForToken',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenID', type: 'uint256' }],
    name: 'getIsSecondaryMarket',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getManagement',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenID', type: 'uint256' }],
    name: 'getRoyalties',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'address', name: 'operator', type: 'address' },
    ],
    name: 'isApprovedForAll',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isEmergencyPause',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
    name: 'isLocked',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'isSecondaryMarket',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_collectionId', type: 'uint256' }],
    name: 'isWithPaymentSplitter',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'keys',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_artist', type: 'address' }],
    name: 'listCollectionsForArtist',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_artist', type: 'address' }],
    name: 'listTokensForArtist',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_collectionID', type: 'uint256' }],
    name: 'listTokensForCollection',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
    name: 'lockId',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'lockMap',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: '_to', type: 'address' },
          { internalType: 'string', name: '_tokenURI', type: 'string' },
          { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
        ],
        internalType: 'struct BoleroNFT.MintData[]',
        name: '_mintData',
        type: 'tuple[]',
      },
    ],
    name: 'mintBatchNFT',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: '_to', type: 'address' },
          { internalType: 'address', name: '_wantToken', type: 'address' },
          { internalType: 'string', name: '_tokenURI', type: 'string' },
          { internalType: 'uint256', name: '_startOffer', type: 'uint256' },
          { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
          { internalType: 'uint256[2]', name: '_startEndTime', type: 'uint256[2]' },
        ],
        internalType: 'struct BoleroNFT.MintAndBidData[]',
        name: '_mintData',
        type: 'tuple[]',
      },
    ],
    name: 'mintBatchNFTAndOpenBidOffer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: '_to', type: 'address' },
          { internalType: 'address', name: '_wantToken', type: 'address' },
          { internalType: 'string', name: '_tokenURI', type: 'string' },
          { internalType: 'uint256', name: '_wantAmount', type: 'uint256' },
          { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
        ],
        internalType: 'struct BoleroNFT.MintAndSellData[]',
        name: '_mintData',
        type: 'tuple[]',
      },
    ],
    name: 'mintBatchNFTAndOpenSellOffer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'string', name: '_tokenURI', type: 'string' },
      { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
    ],
    name: 'mintNFT',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: '_to', type: 'address' },
          { internalType: 'string', name: '_tokenURI', type: 'string' },
          { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
        ],
        internalType: 'struct BoleroNFT.MintData',
        name: '_mintData',
        type: 'tuple',
      },
      { internalType: 'address', name: '_wantToken', type: 'address' },
      { internalType: 'uint256', name: '_startOffer', type: 'uint256' },
      { internalType: 'uint256[2]', name: '_startEndTime', type: 'uint256[2]' },
    ],
    name: 'mintNFTAndOpenBidOffer',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: '_to', type: 'address' },
          { internalType: 'string', name: '_tokenURI', type: 'string' },
          { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
        ],
        internalType: 'struct BoleroNFT.MintData',
        name: '_mintData',
        type: 'tuple',
      },
      { internalType: 'address', name: '_wantToken', type: 'address' },
      { internalType: 'uint256', name: '_wantAmount', type: 'uint256' },
    ],
    name: 'mintNFTAndOpenSellOffer',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'multisigForCollectionID',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'name',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'artistAddress', type: 'address' },
      { internalType: 'address', name: 'collectionPaymentAddress', type: 'address' },
      { internalType: 'address', name: 'privateSaleToken', type: 'address' },
      { internalType: 'string', name: 'collectionName', type: 'string' },
      {
        components: [
          { internalType: 'uint256', name: 'boleroFeesPrimary', type: 'uint256' },
          { internalType: 'uint256', name: 'boleroFeesSecondary', type: 'uint256' },
          { internalType: 'uint256', name: 'artistRoyalties', type: 'uint256' },
        ],
        internalType: 'struct BoleroNFT.Royalties',
        name: '_royalties',
        type: 'tuple',
      },
      { internalType: 'uint256', name: 'cap', type: 'uint256' },
      { internalType: 'uint256', name: 'privateSaleThreshold', type: 'uint256' },
    ],
    name: 'newCollection',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'artistAddress', type: 'address' },
      { internalType: 'address', name: 'privateSaleToken', type: 'address' },
      { internalType: 'string', name: 'collectionName', type: 'string' },
      { internalType: 'address[]', name: '_payees', type: 'address[]' },
      { internalType: 'string[]', name: '_roles', type: 'string[]' },
      { internalType: 'uint256[]', name: '_shares', type: 'uint256[]' },
      {
        components: [
          { internalType: 'uint256', name: 'boleroFeesPrimary', type: 'uint256' },
          { internalType: 'uint256', name: 'boleroFeesSecondary', type: 'uint256' },
          { internalType: 'uint256', name: 'artistRoyalties', type: 'uint256' },
        ],
        internalType: 'struct BoleroNFT.Royalties',
        name: '_royalties',
        type: 'tuple',
      },
      { internalType: 'uint256', name: 'cap', type: 'uint256' },
      { internalType: 'uint256', name: 'privateSaleThreshold', type: 'uint256' },
    ],
    name: 'newCollectionWithPaymentSplitter',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: '_payees', type: 'address[]' },
      { internalType: 'string[]', name: '_roles', type: 'string[]' },
      { internalType: 'uint256[]', name: '_shares', type: 'uint256[]' },
      { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
    ],
    name: 'newPaymentSplitter',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'rewards2981',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'uint256', name: 'value', type: 'uint256' },
    ],
    name: 'royaltyInfo',
    outputs: [
      { internalType: 'address', name: 'receiver', type: 'address' },
      { internalType: 'uint256', name: 'royaltyAmount', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  // {
  //   inputs: [
  //     { internalType: 'address', name: '_from', type: 'address' },
  //     { internalType: 'address', name: '_to', type: 'address' },
  //     { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
  //     { internalType: 'bytes', name: '_data', type: 'bytes' },
  //   ],
  //   name: 'safeTransferFrom',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  {
    inputs: [
      { internalType: 'address', name: 'operator', type: 'address' },
      { internalType: 'bool', name: 'approved', type: 'bool' },
    ],
    name: 'setApprovalForAll',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'setBoleroMultisigImplementation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'setBoleroPaymentSplitterImplementation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_swap', type: 'address' }],
    name: 'setBoleroSwap',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_payment', type: 'address' },
      { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
    ],
    name: 'setCollectionPaymentAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bool', name: 'shouldPause', type: 'bool' }],
    name: 'setEmergencyPause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newRewards2981', type: 'address' }],
    name: 'setRewards',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenID', type: 'uint256' }],
    name: 'setSecondaryMarketStatus',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
      { internalType: 'uint256', name: '_threshold', type: 'uint256' },
    ],
    name: 'setThresholdPrivate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: '_interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
    name: 'tokenByIndex',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'uint256', name: 'index', type: 'uint256' },
    ],
    name: 'tokenOfOwnerByIndex',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_from', type: 'address' },
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
    name: 'unlockId',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: '_contracts', type: 'address[]' },
      { internalType: 'bool[]', name: '_values', type: 'bool[]' },
    ],
    name: 'updateApprovedContracts',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
