import { ContractAbi } from './contract_type';

export const BOLERO_NFT_MANAGER_ABI_V3: ContractAbi = [
  {
    inputs: [
      { internalType: 'address', name: '_admin', type: 'address' },
      { internalType: 'address', name: '_granter', type: 'address' },
      { internalType: 'address', name: '_keeper', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { indexed: true, internalType: 'bytes32', name: 'previousAdminRole', type: 'bytes32' },
      { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
    ],
    name: 'RoleAdminChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
    ],
    name: 'RoleGranted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
    ],
    name: 'RoleRevoked',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'approvedContract', type: 'address' },
    ],
    name: 'TokenLocked',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'approvedContract', type: 'address' },
    ],
    name: 'TokenUnlocked',
    type: 'event',
  },
  {
    inputs: [],
    name: 'ADMIN_ROLE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'BoleroNFT',
    outputs: [{ internalType: 'contract IBoleroNFT', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'BoleroNFTDeployer',
    outputs: [{ internalType: 'contract IBoleroNFTDeployer', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'BoleroNFTSwap',
    outputs: [{ internalType: 'contract IBoleroNFTSwap', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'DEFAULT_ADMIN_ROLE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'GRANTER_ROLE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'KEEPER_ROLE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'OPERATOR_ROLE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'acceptManagement',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'contractAddress', type: 'address' },
      { internalType: 'address', name: 'account', type: 'address' },
      { internalType: 'uint256', name: 'shares', type: 'uint256' },
      { internalType: 'string', name: 'role', type: 'string' },
    ],
    name: 'addPayee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'approvedContract',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenID', type: 'uint256' }],
    name: 'artistPayment',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'boleroPaymentSplitter',
    outputs: [{ internalType: 'contract IPaymentSplitter', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'string', name: '_tokenURI', type: 'string' },
    ],
    name: 'changeTokenURI',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_collectionId', type: 'uint256' }],
    name: 'collectionMultisig',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_collectionId', type: 'uint256' }],
    name: 'collectionPayment',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getApprovedContracts',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenID', type: 'uint256' }],
    name: 'getCollectionIDForToken',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_collectionId', type: 'uint256' }],
    name: 'getCollectionPaymentAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRewards',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
    name: 'getRoleAdmin',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenID', type: 'uint256' }],
    name: 'getRoyalties',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'grantRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: 'recipients', type: 'address[]' },
      { internalType: 'address', name: 'nftAddress', type: 'address' },
      { internalType: 'uint256[]', name: 'tokenIds', type: 'uint256[]' },
    ],
    name: 'grantTokens',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'hasRole',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_boleroDeployer', type: 'address' },
      { internalType: 'address', name: '_boleroNFT', type: 'address' },
      { internalType: 'address', name: '_boleroSwap', type: 'address' },
    ],
    name: 'initializeManager',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
    name: 'isLocked',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_collectionId', type: 'uint256' }],
    name: 'isWithPaymentSplitter',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'keys',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_artist', type: 'address' }],
    name: 'listCollectionsForArtist',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_artist', type: 'address' }],
    name: 'listTokensForArtist',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_collectionID', type: 'uint256' }],
    name: 'listTokensForCollection',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'lockId',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'lockMap',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'management',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'contractAddress', type: 'address' },
      { internalType: 'address', name: 'oldPayee', type: 'address' },
      { internalType: 'address', name: 'newPayee', type: 'address' },
      { internalType: 'string', name: 'role', type: 'string' },
    ],
    name: 'migratePayee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: '_to', type: 'address' },
          { internalType: 'string', name: '_tokenURI', type: 'string' },
          { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
        ],
        internalType: 'struct IBoleroNFT.MintData[]',
        name: '_mintData',
        type: 'tuple[]',
      },
    ],
    name: 'mintBatchNFT',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: '_to', type: 'address' },
          { internalType: 'address', name: '_wantToken', type: 'address' },
          { internalType: 'string', name: '_tokenURI', type: 'string' },
          { internalType: 'uint256', name: '_startOffer', type: 'uint256' },
          { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
          { internalType: 'uint256[2]', name: '_startEndTime', type: 'uint256[2]' },
        ],
        internalType: 'struct IBoleroNFT.MintAndBidData[]',
        name: '_mintData',
        type: 'tuple[]',
      },
    ],
    name: 'mintBatchNFTAndOpenBidOffer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: '_to', type: 'address' },
          { internalType: 'address', name: '_wantToken', type: 'address' },
          { internalType: 'string', name: '_tokenURI', type: 'string' },
          { internalType: 'uint256', name: '_wantAmount', type: 'uint256' },
          { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
        ],
        internalType: 'struct IBoleroNFT.MintAndSellData[]',
        name: '_mintData',
        type: 'tuple[]',
      },
    ],
    name: 'mintBatchNFTAndOpenSellOffer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'string', name: '_tokenURI', type: 'string' },
      { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
    ],
    name: 'mintNFT',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: '_to', type: 'address' },
          { internalType: 'string', name: '_tokenURI', type: 'string' },
          { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
        ],
        internalType: 'struct IBoleroNFT.MintData',
        name: '_mintData',
        type: 'tuple',
      },
      { internalType: 'address', name: '_wantToken', type: 'address' },
      { internalType: 'uint256', name: '_startOffer', type: 'uint256' },
      { internalType: 'uint256[2]', name: '_startEndTime', type: 'uint256[2]' },
    ],
    name: 'mintNFTAndOpenBidOffer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: '_to', type: 'address' },
          { internalType: 'string', name: '_tokenURI', type: 'string' },
          { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
        ],
        internalType: 'struct IBoleroNFT.MintData',
        name: '_mintData',
        type: 'tuple',
      },
      { internalType: 'address', name: '_wantToken', type: 'address' },
      { internalType: 'uint256', name: '_wantAmount', type: 'uint256' },
    ],
    name: 'mintNFTAndOpenSellOffer',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'artistAddress', type: 'address' },
      { internalType: 'address', name: 'collectionPaymentAddress', type: 'address' },
      { internalType: 'address', name: 'privateSaleToken', type: 'address' },
      { internalType: 'string', name: 'collectionName', type: 'string' },
      {
        components: [
          { internalType: 'uint256', name: 'boleroFeesPrimary', type: 'uint256' },
          { internalType: 'uint256', name: 'boleroFeesSecondary', type: 'uint256' },
          { internalType: 'uint256', name: 'artistRoyalties', type: 'uint256' },
        ],
        internalType: 'struct IBoleroNFT.Royalties',
        name: '_royalties',
        type: 'tuple',
      },
      { internalType: 'uint256', name: 'cap', type: 'uint256' },
      { internalType: 'uint256', name: 'privateSaleThreshold', type: 'uint256' },
    ],
    name: 'newCollection',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'artistAddress', type: 'address' },
      { internalType: 'address', name: 'privateSaleToken', type: 'address' },
      { internalType: 'string', name: 'collectionName', type: 'string' },
      { internalType: 'address[]', name: '_payees', type: 'address[]' },
      { internalType: 'string[]', name: '_roles', type: 'string[]' },
      { internalType: 'uint256[]', name: '_shares', type: 'uint256[]' },
      {
        components: [
          { internalType: 'uint256', name: 'boleroFeesPrimary', type: 'uint256' },
          { internalType: 'uint256', name: 'boleroFeesSecondary', type: 'uint256' },
          { internalType: 'uint256', name: 'artistRoyalties', type: 'uint256' },
        ],
        internalType: 'struct IBoleroNFT.Royalties',
        name: '_royalties',
        type: 'tuple',
      },
      { internalType: 'uint256', name: 'cap', type: 'uint256' },
      { internalType: 'uint256', name: 'privateSaleThreshold', type: 'uint256' },
    ],
    name: 'newCollectionWithPaymentSplitter',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: '_payees', type: 'address[]' },
      { internalType: 'string[]', name: '_roles', type: 'string[]' },
      { internalType: 'uint256[]', name: '_shares', type: 'uint256[]' },
      { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
    ],
    name: 'newPaymentSplitter',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'contractAddress', type: 'address' },
      { internalType: 'address', name: '_want', type: 'address' },
    ],
    name: 'releaseToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'renounceRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'revokeRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'rewards',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'rewards2981',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_implementation', type: 'address' }],
    name: 'setBoleroMultisigImplementation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_implementation', type: 'address' }],
    name: 'setBoleroPaymentSplitterImplementation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_boleroSwap', type: 'address' }],
    name: 'setBoleroSwap',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_payment', type: 'address' },
      { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
    ],
    name: 'setCollectionPaymentAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_management', type: 'address' }],
    name: 'setManagement',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_collectionId', type: 'uint256' },
      { internalType: 'uint256', name: '_threshold', type: 'uint256' },
    ],
    name: 'setPrivateThreshold',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_rewards', type: 'address' }],
    name: 'setRewards',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_rewards', type: 'address' }],
    name: 'setRewards2981',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'unlockId',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: '_contracts', type: 'address[]' },
      { internalType: 'bool[]', name: '_values', type: 'bool[]' },
    ],
    name: 'updateApprovedContracts',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'contractAddress', type: 'address' },
      { internalType: 'address', name: 'account', type: 'address' },
      { internalType: 'uint256', name: 'newShares', type: 'uint256' },
    ],
    name: 'updatePayeeShares',
    outputs: [{ internalType: 'bool', name: 'success', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
